FROM node:22-alpine

# BRANDING ARGS passed from docker-compose
ARG BRAND_TITLE
ARG BRAND_LOGO

# Make them available inside Next.js build
ENV BRAND_TITLE=$BRAND_TITLE
ENV BRAND_LOGO=$BRAND_LOGO

ARG NEXT_PUBLIC_VERSION
ENV NEXT_PUBLIC_VERSION=$NEXT_PUBLIC_VERSION

RUN apk add --no-cache g++ make py3-pip bash nginx
RUN adduser -D -g 'www' www
RUN mkdir /www
RUN chown -R www:www /var/lib/nginx
RUN chown -R www:www /www

RUN npm --no-update-notifier --no-fund --global install pnpm@10.6.1 pm2

WORKDIR /app
COPY . /app
COPY var/docker/nginx.conf /etc/nginx/nginx.conf

RUN pnpm install

# Branding vars will now be embedded during build
RUN NODE_OPTIONS="--max-old-space-size=4096" pnpm run build

CMD ["sh", "-c", "nginx && pnpm run pm2"]
